Build:
    stage: build
    image: node:10
    artifacts:
        paths:
          - ./build
    script:
        - pwd
        - source .env
        - echo $REACT_APP_CDN_URL
        - npm i
        - npm run build

Deploy:
    stage: deploy
    image:
        name: banst/awscli
        entrypoint: [""]
    script:
        - ls
        - aws configure set region eu-central-1
        - aws s3 cp ./build s3://$S3_BUCKET/ --recursive
    when: manual
    dependencies:
        - Build